apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dev
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
    resources:
      requests:
        memory: "32Mi"
        cpu: "256m"
      limits:
        memory: "64Mi"
        cpu: "512m"